const config = {
  REACT_APP_BACKEND_URL: process.env.REACT_APP_BACKEND_URL,
  REACT_APP_LINKEDIN_APP_ID: process.env.REACT_APP_LINKEDIN_APP_ID,
  REACT_APP_LINKEDIN_APP_SECRET: process.env.REACT_APP_LINKEDIN_APP_SECRET,
  REACT_APP_INSTAGRAM_APP_ID: process.env.REACT_APP_INSTAGRAM_APP_ID,
  REACT_APP_INSTAGRAM_APP_SECRET:
    process.env.REACT_APP_INSTAGRAM_APP_SECRET,
  REACT_APP_FB_APP_ID: process.env.REACT_APP_FB_APP_ID,
  REACT_APP_TWITTER_V2_APP_KEY: process.env.REACT_APP_TWITTER_V2_APP_KEY,
  REACT_APP_REDIRECT_URI: process.env.REACT_APP_REDIRECT_URI,
};

export default config;
